---
- name: set vars
  set_fact:
    docker_image: docker.io/as202427/ripe-atlas
    docker_container: ripe-atlas
    docker_volume: ripe-atlas_status

- name: Create ripe-atlas etc directory
  ansible.builtin.file:
    path: /var/atlas-probe/etc
    state: directory

- name: Create ripe-atlas status volume
  community.docker.docker_volume:
    name: '{{ docker_volume }}'

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create ripe-atlas container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    env:
      "RXTXRPT": "yes"
    memory: 64m
    memory_reservation: 64m
    mounts:
      - source: /var/atlas-probe/etc
        target: /var/atlas-probe/etc
        type: bind
      - source: '{{ docker_volume }}'
        target: /var/atlas-probe/status
    cap_drop:
      - all
    capabilities:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_RAW
    name: ripe-atlas
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
