---
- name: set vars
  set_fact:
    docker_image: '{{ role_ripe_atlas_image }}'
    docker_container: '{{ role_ripe_atlas_container }}'
    docker_volume_config: '{{ role_ripe_atlas_volume }}_config'
    docker_volume_data: '{{ role_ripe_atlas_volume }}_data'

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create config volume
  community.docker.docker_volume:
    name: "{{ docker_volume_config }}"

- name: Create data volume
  community.docker.docker_volume:
    name: "{{ docker_volume_data }}"

- name: Create ripe-atlas container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    env:
      "RXTXRPT": "yes"
    memory: 64m
    memory_reservation: 64m
    volumes:
     - '{{ docker_volume_config }}:/var/atlas-probe/etc:Z'
     - '{{ docker_volume_data }}:/var/atlas-probe/status:Z'
    cap_drop:
      - all
    capabilities:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_RAW
    name: '{{ docker_container }}'
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
